<h3>Tensorflow Data Pipeline Creation Using Aeroplane and Boat Images</h3>

In [10]:
import tensorflow as tf

In [11]:
images_ds = tf.data.Dataset.list_files('images/*/*', shuffle=False)

In [12]:
image_count = len(images_ds)
image_count

177

In [13]:
type(images_ds)

tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset

In [14]:
for file in images_ds.take(3):
    print(file.numpy())

b'images\\aeroplane\\1200px-Egyptair.a330-200.su-gce.arp.jpg'
b'images\\aeroplane\\360_F_1472821_kMjcU0El8NkcU0k7zNtlVTU0Fl8W2l.jpg'
b'images\\aeroplane\\360_F_20136083_gk0ppzak6UdK9PcDRgPdLjcuAdo7o1LK.jpg'


In [15]:
images_ds = images_ds.shuffle(200)
for file in images_ds.take(3):
    print(file.numpy())

b'images\\boat\\wooden-row-boat-2535042.jpg'
b'images\\boat\\au_.jpg'
b'images\\boat\\640px-1910_Mathis_Launch.jpg'


In [16]:
class_names = ["aeroplane","boat"]

In [17]:
train_size = int(image_count*0.8)
train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [18]:
len(train_ds)

141

In [19]:
len(test_ds)

36

In [20]:
def get_label(file_path):
    import os
    parts = tf.strings.split(file_path, os.path.sep)
    return parts[-2]

In [21]:
get_label("images\\aeroplane\\1200px-Egyptair.a330-200.su-gce.arp.jpg")

<tf.Tensor: shape=(), dtype=string, numpy=b'aeroplane'>

In [22]:
def process_image(file_path):
    label = get_label(file_path)
    img = tf.io.read_file(file_path) 
    img = tf.image.decode_jpeg(img)
    img = tf.image.resize(img, [128, 128])
    return img, label

In [23]:
img, label = process_image("images\\aeroplane\\1200px-Egyptair.a330-200.su-gce.arp.jpg")
img.numpy()[:2]

array([[[156.60571, 164.26978, 181.93774],
        [152.9187 , 165.81104, 181.62427],
        [154.37378, 165.43994, 181.75122],
        [153.68481, 164.7522 , 181.20874],
        [152.5603 , 165.33203, 181.43579],
        [155.79297, 167.60547, 183.66797],
        [152.1272 , 167.     , 182.70776],
        [154.58179, 165.58252, 183.26978],
        [153.70776, 166.14453, 182.01929],
        [154.41553, 168.33594, 181.66797],
        [153.66797, 166.     , 182.     ],
        [157.0039 , 170.3789 , 183.6914 ],
        [159.     , 166.66406, 185.     ],
        [154.68872, 166.73047, 182.73047],
        [155.87671, 169.87671, 182.21265],
        [153.89478, 168.01929, 181.01929],
        [155.31274, 167.31274, 181.31274],
        [154.79297, 165.10547, 179.66797],
        [154.24878, 166.37378, 182.18628],
        [152.98047, 165.35547, 182.66797],
        [155.43945, 168.60327, 182.64575],
        [152.74756, 167.62622, 183.     ],
        [158.4812 , 165.76953, 181.4375 ],
        [15

In [24]:
train_ds = train_ds.map(process_image)
test_ds = test_ds.map(process_image)

In [25]:
for image, label in train_ds.take(1):
    print("****",image)
    print("****",label)

**** tf.Tensor(
[[[2.9232788e-01 1.2869141e+02 2.2269141e+02]
  [1.5042114e-01 1.2856448e+02 2.2256448e+02]
  [0.0000000e+00 1.2916336e+02 2.2316336e+02]
  ...
  [9.9609375e-01 1.2899609e+02 2.1999609e+02]
  [0.0000000e+00 1.2700000e+02 2.1800000e+02]
  [1.9498596e+00 1.2694986e+02 2.1894986e+02]]

 [[0.0000000e+00 1.2848438e+02 2.2305865e+02]
  [0.0000000e+00 1.2972470e+02 2.2372470e+02]
  [0.0000000e+00 1.3000000e+02 2.2400000e+02]
  ...
  [0.0000000e+00 1.2862109e+02 2.1962109e+02]
  [1.6983032e-01 1.2827344e+02 2.1927344e+02]
  [0.0000000e+00 1.2784958e+02 2.1884958e+02]]

 [[0.0000000e+00 1.2951102e+02 2.2326883e+02]
  [2.5543213e-02 1.2906070e+02 2.2306070e+02]
  [0.0000000e+00 1.2978906e+02 2.2578906e+02]
  ...
  [0.0000000e+00 1.3000000e+02 2.2000000e+02]
  [0.0000000e+00 1.2900000e+02 2.1900000e+02]
  [0.0000000e+00 1.2873117e+02 2.1973117e+02]]

 ...

 [[1.3700851e+02 1.9500851e+02 2.4300851e+02]
  [1.3800000e+02 1.9600000e+02 2.4400000e+02]
  [1.3600742e+02 1.9700742e+02 2.4

In [26]:
def scale(image, label):
    return image/255, label

In [27]:
train_ds = train_ds.map(scale)

In [28]:
for image, label in train_ds.take(5):
    print("****Image: ",image.numpy()[0][0])
    print("****Label: ",label.numpy())

****Image:  [0.85882354 0.89411765 0.92941177]
****Label:  b'aeroplane'
****Image:  [0.16473964 0.34513178 0.43924943]
****Label:  b'aeroplane'
****Image:  [0.03223039 0.36041668 0.8650735 ]
****Label:  b'aeroplane'
****Image:  [1. 1. 1.]
****Label:  b'boat'
****Image:  [0.32760608 0.5079982  0.63741   ]
****Label:  b'boat'
